# Generated by Django 5.0.3 on 2024-04-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField(verbose_name='Description')),
                ('location_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations_delivery', to='location.locations', verbose_name='Delivery')),
                ('location_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations_pick_up', to='location.locations', verbose_name='Pick-up')),
            ],
        ),
    ]
